version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - echo "Building"
      - pnpm build
  post_build:
    commands:
      - ls -a
      - cp package.json ./dist
      - cp -r node_modules ./dist
artifacts:
  files:
    - '**/*'
