version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - echo "Building"
      - pnpm build
artifacts:
  files:
    - '**/*'
