version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing dependencies"
      - npm install -g pnpm
      - sudo chown -R ec2-user:ec2-user /var/app
      - pnpm install
  build:
    commands:
      - echo "Building"
      - pnpm build
  post_build:
    commands:
      - ls -a
artifacts:
  files:
    - '**/*'
